### PR TITLE
Configure `rc` channel

### PR DESCRIPTION
**Pull request by LecrisUT**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by LecrisUT** [comment]
Travis CI is not triggerred and I'm not sure how to try and re-trigger it. Maybe with `please rerun bot`?

**Comment by LecrisUT** [comment]
@conda-forge-admin, please rerun bot

**Comment by atztogo** [comment]
@LecrisUT, what can I review?

**Comment by LecrisUT** [comment]
Right now I'm trying to get the `rc` channel to work. Don't know why the GH action failed on the push but not on the PR. On this one, the Travis CI is not being triggered so far.

The main one will still be #82, which we will back-port to main once we release `2.1`.

**Comment by LecrisUT** [comment]
Closing and re-openning triggered the CI, but Travis CI still fails to trigger

**Comment by LecrisUT** [comment]
This PR should reconfigure the builds to allow to upload to the `spglib_rc` channel. Don't know if we also need to add
```yaml
channels:
  targets:
    - [ "conda-forge","main" ]
    - [ "conda-forge","spglib_rc" ]
```

**Comment by LecrisUT** [comment]
Nope, this also did not fix the issue. Will have to open yet another PR to try and configure this.

**Pull request merged**
