### PR TITLE
Try to build for PPC

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by LecrisUT** [comment]
Unfortunately, I don't see PPC in the list of the CI. Are there other projects that include it?

**Comment by jan-janssen** [comment]
> Unfortunately, I don't see PPC in the list of the CI. Are there other projects that include it?

I guess I still have to enable it somewhere else similar like the ARM migration for apple in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt . I asked on the conda-forge Gitter channel, hopefully they can point me in the right direction.

**Comment by jan-janssen** [comment]
Waiting for https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4168

**Comment by jan-janssen** [comment]
Once https://github.com/conda-forge/spglib-feedstock/pull/89 is merged I am going to open a new pull request and try to start over.

**Comment by LecrisUT** [comment]
@jan-janssen Do you need this PR re-opened?

**Comment by jan-janssen** [comment]
@LecrisUT I think we should be fine without reopening it. Thank you

**Comment by LecrisUT** [comment]
Ok, can you confirm that the packages are available for that?

**Comment by jan-janssen** [comment]
The issue is that for some reason the travis tasks were executed during the pull request but not after merging to the master.

**Comment by jan-janssen** [comment]
For example if you compare https://anaconda.org/conda-forge/mpi4py to https://anaconda.org/conda-forge/spglib  then the entries for `linux-aarch64` and `linux-ppc64le` are missing.

**Comment by jan-janssen** [comment]
> https://app.travis-ci.com/github/conda-forge/spglib-feedstock/requests Here it reports `Owner conda-forge user license exceeded.`, might still be ill-configured?

I think that might just be an issue that there are too many requests from the whole conda-forge organization at the moment. Maybe it works with the next release. I remember there was also some way to cross compile but I do not exactly remember how that was done.

**Comment by LecrisUT** [comment]
Let's see if on the rc branch it can be triggerred

**Comment by LecrisUT** [comment]
@jan-janssen can you confirm that we don't need an azure cross-compiler as well? I see there's this line in the azure CI with no equivalent in travis

https://github.com/conda-forge/spglib-feedstock/blob/f0c161b0a78a1b1ffe9539b34a8b6a60b75f5785/.azure-pipelines/azure-pipelines-linux.yml#L13

**Comment by jan-janssen** [comment]
I have to admit I am also new to `ppc` and `arm` for linux. I am going to clarify with the conda-forge core and get back to you.

**Comment by LecrisUT** [comment]
Note: [mpi4py](https://github.com/conda-forge/mpi4py-feedstock) uses azure for the CI, emulating `ppc`. There are `UPLOAD_PACKAGES` available for the travis side, and correctly set, so it should be all well configured. The issue is simply that Travis CI does not run. Due to the `Owner conda-forge user license exceeded.` issue

**Comment by LecrisUT** [comment]
@jan-janssen Problem probably resolved in #92. `rc` branch is currently working. Do you want it back-ported to `main` or can it wait until we release `v2.1.0`?

**Pull request closed without merging**
