### PR TITLE
Try to build only on Azure

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by LecrisUT** [comment]
Please merge onto rc branch instead

**Review by atztogo — APPROVED** [review]

**Comment by atztogo** [comment]
@LecrisUT , Is there any problem to merge onto main?

**Comment by LecrisUT** [comment]
Yes, there is, we will later merge the rc branch to main. It is best to have the setup configured there instead so that we don't have to merge main to rc as well

**Comment by atztogo** [comment]
@jan-janssen, is it OK to merge this PR onto rc branch?

**Pull request closed without merging**
