### PR TITLE
Force openblas numpy

### PR DESCRIPTION
**Pull request by jochym**
To force conda-forge version

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jochym** [comment]
@conda-forge-admin, please rerender

**Comment by jochym** [comment]
OK. Sorry. I thougt the branch is equivalent to the fork for quick changes. I'll cancel this and remoce the branch.

**Comment by isuruf** [comment]
No problem. Let me know which of the packages from https://anaconda.org/conda-forge/spglib/files that needs to be removed. (They were published because of the branch.)

**Comment by jochym** [comment]
Please remove builds _1 and _2 from today. Leave _0 from yesterday in the repo.

**Comment by isuruf** [comment]
I've marked them as broken. Can you confirm that I marked all of them?

**Comment by jochym** [comment]
Yes. Thanks. The _0 are not perfect as well but they are functional and I will fix the rest of the problems in the current PR.

**Pull request closed without merging**
