### PR TITLE
Python 312 with skips

### PR DESCRIPTION
**Pull request by timostrunk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The python 3.12 rollout is being held up by failing builds on aarch64 and ppc64le pypy3.9 in #105 . While this is important to fix, it should be done in a coming PR isolated from the rest of the rollout. In this PR I simply skip the two failing builds. If this PR gets merged, I will immediately send another PR removing the two skips, which fails, like the currently existing python 3.12 rollout PR.

### CODE REVIEW

**Comment by timostrunk** [comment]
@conda-forge-admin, please rerender

**Comment by LecrisUT** [comment]
Thanks for the PR, the issue of the failing builds are rather hard to resolve. I'm thinking of just static linking for those cases after this.

**Review by LecrisUT — APPROVED** [review]

**Comment by timostrunk** [comment]
@LecrisUT thanks for the approval, builds are through

**Comment by LecrisUT** [comment]
Ok, one final thing. Do you know why the tests run so slow? Are they all ran as emulated?

**Comment by timostrunk** [comment]
> Ok, one final thing. Do you know why the tests run so slow? Are they all ran as emulated?

It's not the only feedstock I observed this slowness with recently. My current theory is that this is running on spot instances now and doesn't get compute time. If you look at the logs you see them repeat a lot. I interpret this as spot suspending and resuming. Just a theory though.

**Pull request merged**
